FROM nginx:1.23-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
#COPY html /usr/share/nginx/html
#RUN mkdir /var/www/public -p && touch /var/www/public/index.php
#ENTRYPOINT [ "/docker-entrypoint.sh" ]
#CMD [ "nginx", "-g", "daemon off;" ]